<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Main problems to be answered in this research:</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Regression_Analysis_Oceongrahpic_data_files/libs/clipboard/clipboard.min.js"></script>
<script src="Regression_Analysis_Oceongrahpic_data_files/libs/quarto-html/quarto.js"></script>
<script src="Regression_Analysis_Oceongrahpic_data_files/libs/quarto-html/popper.min.js"></script>
<script src="Regression_Analysis_Oceongrahpic_data_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Regression_Analysis_Oceongrahpic_data_files/libs/quarto-html/anchor.min.js"></script>
<link href="Regression_Analysis_Oceongrahpic_data_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Regression_Analysis_Oceongrahpic_data_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Regression_Analysis_Oceongrahpic_data_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Regression_Analysis_Oceongrahpic_data_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Regression_Analysis_Oceongrahpic_data_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Main problems to be answered in this research:</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><strong>Understanding Oxygen Dynamics in Oceanographic data : The Influence of Environmental Variables</strong></p>
<p><strong>By: Varun Mallela</strong></p>
<p>This research investigates the complex relationships between various oceanographic variables and oxygen concentration within the California Current Ecosystem. Using a subset of the California Cooperative Oceanic Fisheries Investigations (CalCOFI) dataset spanning 2017-2021, I have employed statistical regression techniques to understand how factors such as depth, temperature, salinity, and nutrients influence oxygen dynamics in this region. This analysis builds upon the rich historical CalCOFI dataset collected from 1949-2021. A sample from 2017-2021 was used due to the large size of data in the original dataset which contains records from 1949.</p>
<p>Overall Research on:</p>
<ul>
<li>To investigate relationships between oxygen concentration in oceanographic data and physical and nutrient features through regression modelling.</li>
</ul>
<ol type="1">
<li>Clean the dataset</li>
<li>Check for multi collinearity between independent variables.</li>
<li>Investigate relationships between oxygen concentraion and physical and nutrient features by performing multiple linear regression</li>
<li>Check if depth is a significant predictor for response variable - oxygen concentration using t-test and values from regression summary</li>
<li>Perform a statistical hypothesis test to see if there a significant relationship between any of the predictors (Depthm, T_degC, Salnty, SiO3uM, Phaeop, NO2uM, and NH3uM) and the dissolved oxygen levels (O2ml_L) in seawater - Use ANOVA</li>
<li>Perform Diagnostics for the regression model - Residuals, goodness of fit, feature selection.</li>
<li>Use model selection with various performance metrics like AIC, BIC, MSPE, R^2 and adj R^2 and select best model.</li>
</ol>
<section id="data-cleaning" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning"><strong>Data Cleaning</strong></h3>
<p>Before starting the cleaning process, I want to filter out the rows in my main dataset to only include in the year range 2017-2021. To do this, I’m using another dataset from same source, which has a common key ‘Cst_Cnt’ with my main dataset and also it has year column. So, the idea is to merge the datasets and filter.</p>
<div class="cell" data-outputid="eb77d6a7-cb55-4235-faed-358bdcf31afb" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="268">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Importing Libraries for cleaning</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)   <span class="co"># For data manipulation</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)   <span class="co"># For reading CSV files</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="269">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">options</span>(<span class="at">warn =</span> <span class="sc">-</span><span class="dv">1</span>) <span class="co"># ignoring warnings</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-outputid="1d0205c8-c050-41a6-ba3f-11276a8bbfad" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="270">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>bottle_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Bottle.csv"</span>,<span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="co"># reading the main dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-outputid="c34e170e-cf5f-4bd6-faa9-4a5e4ad8ca2a" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="271">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>cast_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Cast.csv"</span>,<span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="co"># importing another dataset which contains year values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="272">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>filtered_cast <span class="ot">&lt;-</span> cast_df <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Year <span class="sc">&gt;=</span> <span class="dv">2017</span> <span class="sc">&amp;</span> Year <span class="sc">&lt;=</span> <span class="dv">2021</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Cst_Cnt, Year)  <span class="co"># Keep only these columns</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here in the above code, we are filtering columns with year values between 2017-2021.</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="273">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>merged_df <span class="ot">&lt;-</span> <span class="fu">merge</span>(bottle_df, filtered_cast, <span class="at">by =</span> <span class="st">"Cst_Cnt"</span>) <span class="co"># merging the two datasets.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-outputid="0de6f721-1d8d-48dd-fdbe-2b489e5d99ad" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="274">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(merged_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A data.frame: 1 × 1</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" scope="col">n</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th" scope="col">&lt;int&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>30508</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We can see that we have a total of 30508 values to work with our analysis.</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="275">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(merged_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   30508 obs. of  63 variables:
 $ Cst_Cnt            : num  34405 34405 34405 34405 34405 ...
 $ Btl_Cnt            : num  864864 864865 864866 864867 864868 ...
 $ Sta_ID             : chr  "063.3 052.0" "063.3 052.0" "063.3 052.0" "063.3 052.0" ...
 $ Depth_ID           : chr  "20-1701RL-MX-027-1949-06330520-0000A-7" "20-1701RL-MX-027-1949-06330520-0010A-7" "20-1701RL-MX-027-1949-06330520-0020A-7" "20-1701RL-MX-027-1949-06330520-0030A-7" ...
 $ Depthm             : num  0 10 20 30 50 75 0 10 20 30 ...
 $ T_degC             : num  12.3 12.3 12.2 12.3 12.2 ...
 $ Salnty             : num  33.2 33.2 33.2 33.2 33.3 ...
 $ O2ml_L             : num  5.92 5.92 5.88 5.8 5.34 ...
 $ STheta             : num  25.1 25.1 25.1 25.1 25.2 ...
 $ O2Sat              : num  97.3 97.2 96.6 95.3 87.7 ...
 $ Oxy_µmol/Kg        : num  258 258 256 253 233 ...
 $ BtlNum             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ RecInd             : num  7 7 7 7 7 7 7 7 7 7 ...
 $ T_prec             : num  2 2 2 2 2 2 2 2 2 2 ...
 $ T_qual             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ S_prec             : num  3 3 3 3 3 3 3 3 3 3 ...
 $ S_qual             : num  6 6 6 6 6 6 6 6 6 6 ...
 $ P_qual             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ O_qual             : num  6 6 6 6 6 6 6 6 6 6 ...
 $ SThtaq             : num  6 6 6 6 6 6 6 6 6 6 ...
 $ O2Satq             : num  6 6 6 6 6 6 6 6 6 6 ...
 $ ChlorA             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ Chlqua             : num  9 9 9 9 9 9 9 9 9 9 ...
 $ Phaeop             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ Phaqua             : num  9 9 9 9 9 9 9 9 9 9 ...
 $ PO4uM              : num  NA NA NA NA NA NA NA NA NA NA ...
 $ PO4q               : num  9 9 9 9 9 9 9 9 9 9 ...
 $ SiO3uM             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ SiO3qu             : num  9 9 9 9 9 9 9 9 9 9 ...
 $ NO2uM              : num  NA NA NA NA NA NA NA NA NA NA ...
 $ NO2q               : num  9 9 9 9 9 9 9 9 9 9 ...
 $ NO3uM              : num  NA NA NA NA NA NA NA NA NA NA ...
 $ NO3q               : num  9 9 9 9 9 9 9 9 9 9 ...
 $ NH3uM              : num  NA NA NA NA NA NA NA NA NA NA ...
 $ NH3q               : num  9 9 9 9 9 9 9 9 9 9 ...
 $ C14As1             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ C14A1p             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ C14A1q             : num  9 9 9 9 9 9 9 9 9 9 ...
 $ C14As2             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ C14A2p             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ C14A2q             : num  9 9 9 9 9 9 9 9 9 9 ...
 $ DarkAs             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ DarkAp             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ DarkAq             : num  9 9 9 9 9 9 9 9 9 9 ...
 $ MeanAs             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ MeanAp             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ MeanAq             : num  9 9 9 9 9 9 9 9 9 9 ...
 $ IncTim             : 'hms' num  NA NA NA NA ...
  ..- attr(*, "units")= chr "secs"
 $ LightP             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ R_Depth            : num  0 10 20 30 50 76 0 10 20 30 ...
 $ R_TEMP             : num  12.3 12.3 12.2 12.3 12.2 ...
 $ R_Sal              : num  283 283 283 282 274 ...
 $ R_DYNHT            : num  0 0.014 0.043 0.071 0.127 0.194 0 0.014 0.043 0.071 ...
 $ R_Nuts             : num  NA NA NA NA NA NA NA NA NA NA ...
 $ R_Oxy_µmol/Kg      : num  258 258 256 253 233 ...
 $ DIC1               : num  NA NA NA NA NA NA NA NA NA NA ...
 $ DIC2               : logi  NA NA NA NA NA NA ...
 $ TA1                : num  NA NA NA NA NA NA NA NA NA NA ...
 $ TA2                : logi  NA NA NA NA NA NA ...
 $ pH1                : logi  NA NA NA NA NA NA ...
 $ pH2                : logi  NA NA NA NA NA NA ...
 $ DIC Quality Comment: logi  NA NA NA NA NA NA ...
 $ Year               : num  2017 2017 2017 2017 2017 ...</code></pre>
</div>
</div>
<p>From the above code, we can see all the variables present in my dataset, my main foucus is to take ‘O2ml_L’ which is milliliters of dissolved oxygen per liter seawater as my dependent variable and do my regression analysis. Many variables in my dataset are unnecessary for my analysis, most of the variables are either quality codes or index variables. So, I plan to first remove the variables no needed for my analysis.</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="276">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>keep_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Depthm"</span>, <span class="st">"T_degC"</span>, <span class="st">"Salnty"</span>, <span class="st">"PO4uM"</span>, <span class="st">"SiO3uM"</span>, <span class="st">"NO3uM"</span>, <span class="st">"O2ml_L"</span>,<span class="st">'Phaeop'</span>, <span class="st">'NO2uM'</span>, <span class="st">'NH3uM'</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop unnecessary columns</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>merged_df <span class="ot">&lt;-</span> merged_df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">all_of</span>(keep_cols))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I have choosen the following variables for my analysis:</p>
<p><strong>Core Physical Factors</strong>:</p>
<p>Depthm (Depth in meters) T_degC (Temperature of water) Salnty (Salinity of water )</p>
<p><strong>Nutrients</strong>:</p>
<p>PO4µM Phosphate concentratione) SiO3µM (Silicat concentratione) NO3µM (Nitrat concentratione) Phaeo (Phaeophytin concentration measured fluorometrically)p NO2u (Nitrite concentration )M NH3 (Ammonium concentration )uM</p>
<div class="cell" data-outputid="b5ec57cd-f933-4584-a79f-976303aa3a1c" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="277">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">colnames</span>(merged_df))  <span class="co"># This will output a character vector of column names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Depthm" "T_degC" "Salnty" "PO4uM"  "SiO3uM" "NO3uM"  "O2ml_L" "Phaeop"
 [9] "NO2uM"  "NH3uM" </code></pre>
</div>
</div>
<p>Now, first I will be checking for missing values</p>
<div class="cell" data-outputid="cc38c3df-35bf-40ec-e6e6-f0ba505a11ba" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="278">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>missing_counts <span class="ot">&lt;-</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(merged_df))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Depthm T_degC Salnty  PO4uM SiO3uM  NO3uM O2ml_L Phaeop  NO2uM  NH3uM 
     0      6      2   2916   2914   2913   1079  10114   3642   4981 </code></pre>
</div>
</div>
<p>We can see from the above output that, variables temperature and salinity have vary less missing values, so I plan to remove rows of missing values of these variables.</p>
<p>For other nutrient variables, there are quite a number of missing values, I plan to check for skewness and decide which type of imputation method (mean/mode) to use to fix those missing values.</p>
<div class="cell" data-outputid="785d870e-0f9a-4379-ecd1-149924b25adb" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="279">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(merged_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>     Depthm          T_degC           Salnty           PO4uM      
 Min.   :  0.0   Min.   : 4.757   Min.   : 9.501   Min.   :0.000  
 1st Qu.: 30.0   1st Qu.: 8.292   1st Qu.:33.453   1st Qu.:0.330  
 Median :100.0   Median :10.572   Median :33.672   Median :1.485  
 Mean   :154.5   Mean   :11.361   Mean   :33.501   Mean   :1.459  
 3rd Qu.:250.0   3rd Qu.:14.325   3rd Qu.:34.056   3rd Qu.:2.380  
 Max.   :751.0   Max.   :99.000   Max.   :34.403   Max.   :4.110  
                 NA's   :6        NA's   :2        NA's   :2916   
     SiO3uM           NO3uM           O2ml_L             Phaeop      
 Min.   :  0.00   Min.   : 0.00   Min.   :-200.222   Min.   :-1.899  
 1st Qu.:  2.44   1st Qu.: 0.57   1st Qu.:   1.761   1st Qu.: 0.049  
 Median : 17.83   Median :18.59   Median :   3.669   Median : 0.108  
 Mean   : 24.88   Mean   :17.37   Mean   :   3.577   Mean   : 0.186  
 3rd Qu.: 41.70   3rd Qu.:30.50   3rd Qu.:   5.617   3rd Qu.: 0.232  
 Max.   :113.24   Max.   :43.08   Max.   :   9.539   Max.   : 4.037  
 NA's   :2914     NA's   :2913    NA's   :1079       NA's   :10114   
     NO2uM           NH3uM       
 Min.   :0.000   Min.   : 0.000  
 1st Qu.:0.000   1st Qu.: 0.000  
 Median :0.000   Median : 0.000  
 Mean   :0.037   Mean   : 0.063  
 3rd Qu.:0.034   3rd Qu.: 0.000  
 Max.   :1.289   Max.   :33.580  
 NA's   :3642    NA's   :4981    </code></pre>
</div>
</div>
<p>Before proceeding I have printed the summary statistics of all variables, later I will make to compare this statistics after cleaning to ensure there was no major change.</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="280">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>merged_df <span class="ot">&lt;-</span> merged_df <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(T_degC) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(Salnty))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I have removed null values from temperature and salinity variables.</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="281">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>merged_df <span class="ot">&lt;-</span> merged_df <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>   <span class="fu">filter</span>(O2ml_L <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">filter</span>(Phaeop <span class="sc">&gt;</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I have removed negative values from oxygen concentration and Phaeophytin concentration columns</p>
<p><strong>Checking For Skewness For nutrient variables uisng density plots</strong></p>
<div class="cell" data-outputid="ff1e1a86-c7de-4223-dd65-83d8891ce3e2" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="282">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># List of variables to plot</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>variables <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"PO4uM"</span> ,<span class="st">"SiO3uM"</span> ,<span class="st">"NO3uM"</span>,  <span class="st">"O2ml_L"</span>, <span class="st">"Phaeop"</span>, <span class="st">'NO2uM'</span>,  <span class="st">'NH3uM'</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating individual plots for each variable</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (var <span class="cf">in</span> variables) {</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(merged_df, <span class="fu">aes</span>(<span class="at">x =</span> .data[[var]])) <span class="sc">+</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density</span>()<span class="sc">+</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> var, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(plot)</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-16-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-16-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-16-output-3.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-16-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-16-output-5.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-16-output-6.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-16-output-7.png" class="img-fluid"></p>
</div>
</div>
<p>From the above plots we can see that all these variables are skewed and dont follow a normal distribution, so I will be using median for my imputation methods</p>
<div class="cell" data-outputid="1b475989-c5dc-488b-f0f7-8a6a20669f9a" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="283">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("tidyverse")</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the dplyr package</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace missing values with the median for the specified columns</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>merged_df <span class="ot">&lt;-</span> merged_df <span class="sc">%&gt;%</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">PO4uM =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(PO4uM), <span class="fu">median</span>(PO4uM, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), PO4uM),</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">SiO3uM =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(SiO3uM), <span class="fu">median</span>(SiO3uM, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), SiO3uM),</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">NO3uM =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(NO3uM), <span class="fu">median</span>(NO3uM, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), NO3uM),</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">O2ml_L =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(O2ml_L), <span class="fu">median</span>(O2ml_L, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), O2ml_L),</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">Phaeop =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(Phaeop), <span class="fu">median</span>(Phaeop, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), Phaeop),</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">NO2uM  =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(NO2uM), <span class="fu">median</span>(NO2uM, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), NO2uM),</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">NH3uM  =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(NH3uM), <span class="fu">median</span>(NH3uM, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), NH3uM)</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking the summary to confirm changes</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(merged_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>     Depthm           T_degC           Salnty          PO4uM      
 Min.   :  0.00   Min.   : 7.636   Min.   :24.19   Min.   :0.000  
 1st Qu.: 20.00   1st Qu.:10.071   1st Qu.:33.39   1st Qu.:0.270  
 Median : 61.00   Median :12.612   Median :33.55   Median :0.680  
 Mean   : 72.85   Mean   :12.883   Mean   :33.32   Mean   :0.912  
 3rd Qu.:121.00   3rd Qu.:15.163   3rd Qu.:33.74   3rd Qu.:1.550  
 Max.   :204.00   Max.   :23.145   Max.   :34.32   Max.   :3.560  
     SiO3uM           NO3uM            O2ml_L          Phaeop      
 Min.   :  0.00   Min.   : 0.000   Min.   :0.915   Min.   :0.0010  
 1st Qu.:  1.82   1st Qu.: 0.050   1st Qu.:3.424   1st Qu.:0.0490  
 Median :  5.95   Median : 5.980   Median :5.209   Median :0.1080  
 Mean   : 10.97   Mean   : 9.778   Mean   :4.616   Mean   :0.1867  
 3rd Qu.: 19.22   3rd Qu.:19.648   3rd Qu.:5.763   3rd Qu.:0.2320  
 Max.   :109.47   Max.   :34.000   Max.   :9.539   Max.   :4.0370  
     NO2uM             NH3uM         
 Min.   :0.00000   Min.   : 0.00000  
 1st Qu.:0.00000   1st Qu.: 0.00000  
 Median :0.01600   Median : 0.00000  
 Mean   :0.04938   Mean   : 0.07306  
 3rd Qu.:0.05000   3rd Qu.: 0.02000  
 Max.   :1.28900   Max.   :33.58000  </code></pre>
</div>
</div>
<p>Due to the presence of skewness I have replaced null values in these nutrient columns with median. I have printed summary statistics to check if there was any significant changes after imputation. From the summary I can say that there was not a significant change after imputation.</p>
<p>From the summary statistics, we can see that for some columns there are some maximum values which are unrealistic, so I decided to remove them.</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="284">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Removing very large values, possible error values due to very high unrealistic values</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>merged_df <span class="ot">&lt;-</span> <span class="fu">subset</span>(merged_df, SiO3uM <span class="sc">!=</span> <span class="fl">109.47</span> )</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>merged_df <span class="ot">&lt;-</span> <span class="fu">subset</span>(merged_df,  NH3uM  <span class="sc">!=</span> <span class="fl">33.58000</span> )</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>merged_df <span class="ot">&lt;-</span> <span class="fu">subset</span>(merged_df,  NO3uM  <span class="sc">!=</span> <span class="fl">34.000</span> )</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>merged_df <span class="ot">&lt;-</span> <span class="fu">subset</span>(merged_df,  Depthm  <span class="sc">!=</span> <span class="fl">204.00</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="285">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(merged_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A data.frame: 6 × 10</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">Depthm</th>
<th data-quarto-table-cell-role="th" scope="col">T_degC</th>
<th data-quarto-table-cell-role="th" scope="col">Salnty</th>
<th data-quarto-table-cell-role="th" scope="col">PO4uM</th>
<th data-quarto-table-cell-role="th" scope="col">SiO3uM</th>
<th data-quarto-table-cell-role="th" scope="col">NO3uM</th>
<th data-quarto-table-cell-role="th" scope="col">O2ml_L</th>
<th data-quarto-table-cell-role="th" scope="col">Phaeop</th>
<th data-quarto-table-cell-role="th" scope="col">NO2uM</th>
<th data-quarto-table-cell-role="th" scope="col">NH3uM</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
<th data-quarto-table-cell-role="th" scope="col">&lt;dbl&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">1</td>
<td>0</td>
<td>13.013</td>
<td>33.3230</td>
<td>0.73</td>
<td>7.43</td>
<td>5.80</td>
<td>5.615</td>
<td>0.486</td>
<td>0.245</td>
<td>0.08</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">2</td>
<td>1</td>
<td>13.013</td>
<td>33.3230</td>
<td>0.73</td>
<td>7.43</td>
<td>5.80</td>
<td>5.615</td>
<td>0.486</td>
<td>0.245</td>
<td>0.08</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">3</td>
<td>6</td>
<td>13.010</td>
<td>33.3200</td>
<td>0.73</td>
<td>7.36</td>
<td>5.73</td>
<td>5.633</td>
<td>0.366</td>
<td>0.244</td>
<td>0.14</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">4</td>
<td>10</td>
<td>13.001</td>
<td>33.3268</td>
<td>0.73</td>
<td>7.45</td>
<td>5.87</td>
<td>5.620</td>
<td>0.425</td>
<td>0.246</td>
<td>0.15</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">5</td>
<td>20</td>
<td>12.913</td>
<td>33.3374</td>
<td>0.74</td>
<td>7.69</td>
<td>6.19</td>
<td>5.504</td>
<td>0.409</td>
<td>0.253</td>
<td>0.20</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">6</td>
<td>30</td>
<td>12.883</td>
<td>33.3468</td>
<td>0.77</td>
<td>7.82</td>
<td>6.40</td>
<td>5.439</td>
<td>0.424</td>
<td>0.260</td>
<td>0.22</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The cleaning process is completed and, we can the see the head of the final dataset which will be now used for regression analysis.</p>
</section>
<section id="regression-modelling" class="level3">
<h3 class="anchored" data-anchor-id="regression-modelling"><strong>Regression Modelling</strong></h3>
<p>Assumption of Regression Model:</p>
<ol type="1">
<li><p>Linearity - There must be a linear relationship between the response variable and the independent variables.</p></li>
<li><p>Multivariate Normality - We assume that residuals are normally distributed.</p></li>
<li><p>No Multicollinearity - We assume that the independent variable are not highly correlated with each other.</p></li>
<li><p>Homoscedasticity - We assume that the variance of error terms is similar across the values of the independent variables.</p></li>
</ol>
<div class="cell" data-outputid="37653d31-c636-4343-c16b-a866fd35832a" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="286">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">145764</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">floor</span>(<span class="fl">0.8</span> <span class="sc">*</span> <span class="fu">nrow</span>(merged_df)) <span class="co">#find the number corresponding to 80% of the data</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>index <span class="ot">=</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(merged_df)), <span class="at">size =</span> n) <span class="co">#randomly sample indicies to be included in the training set</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>train <span class="ot">=</span> merged_df[index, ] <span class="co">#set the training set to be the randomly sampled rows of the dataframe</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>test <span class="ot">=</span> merged_df[<span class="sc">-</span>index, ] <span class="co">#set the testing set to be the remaining rows</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"There are"</span>, <span class="fu">dim</span>(train)[<span class="dv">1</span>], <span class="st">"rows and"</span>,<span class="fu">dim</span>(train)[<span class="dv">2</span>],<span class="st">"columns in the training set. "</span>)  <span class="co">#checking the dimensions</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"There are"</span>, <span class="fu">dim</span>(test)[<span class="dv">1</span>], <span class="st">"rows and"</span>,<span class="fu">dim</span>(test)[<span class="dv">2</span>],<span class="st">"columns in the testing set."</span>)  <span class="co">#checking the dimensions</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>There are 16238 rows and 10 columns in the training set. There are 4060 rows and 10 columns in the testing set.</code></pre>
</div>
</div>
<p>To start of the regression modelling, I have first randomly split my dataset into train and split set, with 80% of the data for training and 20% of data for testing.</p>
<p>In my analysis, I will first of check for presence of multicollinearity and remove it to ensure proper results i.e to ensure statistical significance of independent variables</p>
<p>Correlation Plot</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="287">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"corrplot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-outputid="bc457936-24e4-4e01-bbff-cd5f50e46934" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="288">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'corrplot'</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>col4 <span class="ot">=</span> <span class="fu">colorRampPalette</span>(<span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"darkgrey"</span>, <span class="st">"grey"</span>,<span class="st">"#CFB87C"</span>))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(<span class="fu">cor</span>(merged_df[,<span class="sc">-</span><span class="dv">8</span>]), <span class="at">method =</span> <span class="st">"ellipse"</span>, <span class="at">col =</span> <span class="fu">col4</span>(<span class="dv">100</span>),  <span class="at">addCoef.col =</span> <span class="st">"black"</span>, <span class="at">tl.col =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-22-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>I have then plotted a correlation, plot to understand which independent variables are correleted among each other. From the plot I can see that the variables ‘PO4uM’, ‘NO3uM’, and ‘SiO3uM’ exihibt high correlation between other variables. This arries a problem of multicollinearity. To verify this futher and to decide whether to keep these variables I will be using VIF values.</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="289">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(O2ml_L <span class="sc">~</span> Depthm <span class="sc">+</span>T_degC <span class="sc">+</span> Salnty <span class="sc">+</span>PO4uM<span class="sc">+</span>SiO3uM<span class="sc">+</span> NO3uM<span class="sc">+</span>Phaeop<span class="sc">+</span>NO2uM<span class="sc">+</span>NH3uM, <span class="at">data =</span> train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I have use lm function to model a multiple linear regression model with oxygen concentration beign my dependent variable.</p>
<div class="cell" data-outputid="fbedd06e-e991-44bc-e533-6ba44b4279ff" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="290">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>calculate_vifs <span class="ot">&lt;-</span> <span class="cf">function</span>(model) {</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">vif</span>(model)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>vifs <span class="ot">&lt;-</span> <span class="fu">calculate_vifs</span>(model)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>cond_number <span class="ot">&lt;-</span> <span class="fu">kappa</span>(model)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"VIFs:"</span>)</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(vifs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "VIFs:"
    Depthm     T_degC     Salnty      PO4uM     SiO3uM      NO3uM     Phaeop 
  4.379273   6.482290   1.046232 136.878649  31.502541 104.245633   1.482422 
     NO2uM      NH3uM 
  1.543590   1.240594 </code></pre>
</div>
</div>
<p>From the above VIF values we can see the all the mentioned above variables - ‘PO4uM’, ‘NO3uM’, and ‘SiO3uM’ have very high values than normal threshold. So I plan to remove 2 of these values and check again, so I will be removing - ‘PO4uM’, ‘NO3uM’ since these variables have VIF values more than 100.</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="291">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(O2ml_L <span class="sc">~</span> Depthm <span class="sc">+</span> T_degC <span class="sc">+</span> Salnty <span class="sc">+</span> SiO3uM <span class="sc">+</span> Phaeop <span class="sc">+</span> NO2uM <span class="sc">+</span> NH3uM , <span class="at">data =</span> train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="293">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>vifs <span class="ot">&lt;-</span> <span class="fu">calculate_vifs</span>(model)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>cond_number <span class="ot">&lt;-</span> <span class="fu">kappa</span>(model)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"VIFs:"</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(vifs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "VIFs:"
  Depthm   T_degC   Salnty   SiO3uM   Phaeop    NO2uM    NH3uM 
4.079090 4.167353 1.034154 3.312954 1.426863 1.490178 1.226217 </code></pre>
</div>
</div>
<p>After removing the two variables, we can see from the above output that all the VIF values are below 5, so we can say that there no collinearity present here according to the above results.</p>
<p>Now let’s, focus on this new model let’s see its summary.</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="294">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>
Call:
lm(formula = O2ml_L ~ Depthm + T_degC + Salnty + SiO3uM + Phaeop + 
    NO2uM + NH3uM, data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.7665 -0.2659  0.0344  0.3043  8.0885 

Coefficients:
              Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)  6.4449114  0.1014648   63.519   &lt;2e-16 ***
Depthm      -0.0023178  0.0001356  -17.098   &lt;2e-16 ***
T_degC       0.0649608  0.0026139   24.852   &lt;2e-16 ***
Salnty      -0.0483205  0.0028386  -17.023   &lt;2e-16 ***
SiO3uM      -0.0865234  0.0006587 -131.361   &lt;2e-16 ***
Phaeop       0.3314825  0.0198599   16.691   &lt;2e-16 ***
NO2uM       -0.0897524  0.0526548   -1.705   0.0883 .  
NH3uM        0.0141123  0.0142852    0.988   0.3232    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5051 on 16230 degrees of freedom
Multiple R-squared:  0.8603,    Adjusted R-squared:  0.8602 
F-statistic: 1.428e+04 on 7 and 16230 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The above summary suggest that 86% of variance dissolved in oxygen levels is explained by the model. We can see that all the predictors except ‘NO2uM’ and ‘NH3uM’ are statistically very good predictors with the response variable - O2ml_L i.e.&nbsp;oxygen concentration.</p>
</section>
<section id="hypothesis-test---t-test" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis-test---t-test"><strong>Hypothesis Test - t test</strong></h3>
<p>Let’s verify this by using t -test with to check if Depthm is a significant predictor for the response variable - O2ml_L.</p>
</section>
<section id="step-1-formulate-hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="step-1-formulate-hypotheses">Step 1: Formulate Hypotheses</h3>
<ul>
<li><p><strong>Null Hypothesis (H₀)</strong>: The coefficient for <code>Depthm</code> is equal to zero (<span class="math inline">\(\beta_{Depthm} = 0\)</span>), this implyes that there is no significant relationship between <code>Depthm</code> and <code>O2ml_L</code>.</p></li>
<li><p><strong>Alternative Hypothesis (H₁)</strong>: The coefficient for <code>Depthm</code> is not equal to zero (<span class="math inline">\(\beta_{Depthm} \neq 0\)</span>), this implies that there is a significant relationship between <code>Depthm</code> and <code>O2ml_L</code>.</p></li>
</ul>
<p>Significance level : 0.05</p>
</section>
<section id="step-2-calculating-the-test-statistic" class="level3">
<h3 class="anchored" data-anchor-id="step-2-calculating-the-test-statistic">Step 2: Calculating the Test Statistic</h3>
<p>The t-statistic can be calculated using the formula: <span class="math display">\[
t = \frac{\hat{\beta}_{Depthm}}{SE_{\beta_{Depthm}}}
\]</span></p>
<p>From the regression summary we have: - <span class="math inline">\(\hat{\beta}_{Depthm} = -0.0023178\)</span> - <span class="math inline">\(SE_{\beta_{Depthm}} = 0.0001356\)</span></p>
<p><span class="math display">\[
t = \frac{-0.0023178}{0.0001356} \approx -17.098
\]</span></p>
</section>
<section id="step-3-determining-the-degrees-of-freedom" class="level3">
<h3 class="anchored" data-anchor-id="step-3-determining-the-degrees-of-freedom">Step 3: Determining the Degrees of Freedom</h3>
<p>The degrees of freedom (df) for the test can calculated as <span class="math display">\[ n - p - 1 \]</span>, where: - <span class="math display">\[n = 16238\]</span> (total number of observations) - <span class="math display">\[p = 7\]</span> (number of predictors)</p>
<p>$ df = 16230 $</p>
</section>
<section id="step-4-determining-the-critical-value-and-p-value" class="level3">
<h3 class="anchored" data-anchor-id="step-4-determining-the-critical-value-and-p-value">Step 4: Determining the Critical Value and p-value</h3>
<p>With <span class="math display">\[df = 16230\]</span>, the p-value for <code>Depthm</code>is given in summary of regression model:</p>
<ul>
<li><strong>p-value</strong>: <span class="math inline">\(&lt;2e-16\)</span>, which is extremely small.</li>
</ul>
</section>
<section id="step-5-conclusion" class="level3">
<h3 class="anchored" data-anchor-id="step-5-conclusion">Step 5: Conclusion</h3>
<p>Based on the p-value, which is much smaller significance level 0.05 we reject the null hypothesis. This indicates that there is a statistically significant relationship between <code>Depthm</code> and <code>O2ml_L</code>.</p>
<p>The negative coefficient of (<span class="math inline">\(-0.0023178\)</span>) suggests that as <code>Depthm</code> increases, the dissolved oxygen level (<code>O2ml_L</code>) decreases.</p>
<p>Now lets perform a statistical hypothesis test to see if there a significant relationship between any of the predictors (Depthm, T_degC, Salnty, SiO3uM, Phaeop, NO2uM, and NH3uM) and the dissolved oxygen levels (O2ml_L) in seawater. I will be using ANOVA for this.</p>
</section>
<section id="anova" class="level3">
<h3 class="anchored" data-anchor-id="anova">ANOVA</h3>
<p>Assumptions of the ANOVA test: - The observations are independent and randomly obtained from the population defined by the factor levels. - The data in each group (factor level) is normally distributed. - The data in each group has the same variance.</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="295">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting the linear model</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(O2ml_L <span class="sc">~</span> Depthm <span class="sc">+</span> T_degC <span class="sc">+</span> Salnty <span class="sc">+</span> SiO3uM <span class="sc">+</span> Phaeop <span class="sc">+</span> NO2uM <span class="sc">+</span> NH3uM, <span class="at">data =</span> train)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Performing an ANOVA test</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>anova_results <span class="ot">&lt;-</span> <span class="fu">anova</span>(model)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="co"># View the ANOVA table</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(anova_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: O2ml_L
             Df  Sum Sq Mean Sq    F value Pr(&gt;F)    
Depthm        1 18558.5 18558.5 72732.6462 &lt;2e-16 ***
T_degC        1  2321.8  2321.8  9099.2837 &lt;2e-16 ***
Salnty        1    67.5    67.5   264.3939 &lt;2e-16 ***
SiO3uM        1  4475.8  4475.8 17541.1307 &lt;2e-16 ***
Phaeop        1    76.2    76.2   298.5607 &lt;2e-16 ***
NO2uM         1     0.5     0.5     2.0971 0.1476    
NH3uM         1     0.2     0.2     0.9760 0.3232    
Residuals 16230  4141.3     0.3                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>From the above ANOVA result we can formulate and conclude the following:</p>
<p>significane level is 0.01 ### Hypotheses - <strong>Null Hypothesis (H₀)</strong>: None of the predictors (Depthm, T_degC, Salnty, SiO3uM, Phaeop, NO2uM, and NH3uM) have a statistically significant relationship with the response variable, O2ml_L (all coefficients are zero).</p>
<ul>
<li><strong>Alternative Hypothesis (H₁)</strong>: At least one predictor has a statistically significant relationship with the response variable, O2ml_L. (Atleast one coefficient is different from zero)</li>
</ul>
</section>
<section id="results-from-anova-table" class="level3">
<h3 class="anchored" data-anchor-id="results-from-anova-table">Results from ANOVA Table</h3>
<ul>
<li><strong>Depthm</strong>: F(1, 16230) = 72732.65, p &lt; 2e-16. Here the pvalue is very small, so this indicates a significant relationship.</li>
<li><strong>T_degC</strong>: F(1, 16230) = 9099.28, p &lt; 2e-16. Here the pvalue is very small, so this indicates a significant relationship.</li>
<li><strong>Salnty</strong>: F(1, 16230) = 264.39, p &lt; 2e-16. Here the pvalue is very small, so this indicates a significant relationship.</li>
<li><strong>SiO3uM</strong>: F(1, 16230) = 17541.13, p &lt; 2e-16. Here the pvalue is very small, so this indicates a significant relationship.</li>
<li><strong>Phaeop</strong>: F(1, 16230) = 298.56, p &lt; 2e-16. Here the pvalue is very small, so this indicates a significant relationship.</li>
<li><strong>NO2uM</strong>: F(1, 16230) = 2.10, p = 0.1476. Here the pvalue is greater than 0.01 significance so, this suggests no significant relationship.</li>
<li><strong>NH3uM</strong>: F(1, 16230) = 0.98, p = 0.3232. Here the pvalue is greater than 0.01 significance so, this suggests no significant relationship.</li>
</ul>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>Based on the ANOVA table we can conclude the following: - Since we have more than one variable which has significant relation with the response variable , there is significant evidence to reject the null hypothesis at the α = 0.01 level. So, this indicates that at least one of the predictors (Depthm, T_degC, Salnty, SiO3uM, or Phaeop) is significantly associated with the response variable, O2ml_L. - NO2uM and NH3uM do not significantly explain the variance in O2ml_L, as their p-values are greater than 0.01.</p>
<p>Now let’s move on to peform the diagnostics for the regression model, this will be helpful to check if our assumptions for regression modelling and ANOVA performed earlier are valid.</p>
</section>
<section id="diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="diagnostics">Diagnostics</h3>
<section id="residual-analysis" class="level4">
<h4 class="anchored" data-anchor-id="residual-analysis">Residual Analysis</h4>
</section>
<section id="checking-for-constant-variance" class="level4">
<h4 class="anchored" data-anchor-id="checking-for-constant-variance">1) Checking for Constant Variance</h4>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="296">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>df.diagnostics <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">yhat =</span> <span class="fu">fitted</span>(model), <span class="at">r =</span> <span class="fu">residuals</span>(model))</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Residuals vs fitted Plot</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df.diagnostics, <span class="fu">aes</span>(<span class="at">x =</span> yhat, <span class="at">y =</span> r)) <span class="sc">+</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> F, <span class="at">col =</span> <span class="st">"#CFB87C"</span>) <span class="sc">+</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Fitted Values"</span>) <span class="sc">+</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Residuals"</span>) <span class="sc">+</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Residuals vs Fitted Plot Plot"</span>)<span class="sc">+</span></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-29-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>From the above Residuals vs Fitted plot we can see presence of some outliers and also right towards the end of the plot there are many values which have a lower value compared to others. There is a clear visible downward spike, so we can say that constant variance assumption has been violated here.</p>
</section>
<section id="checking-for-normality" class="level4">
<h4 class="anchored" data-anchor-id="checking-for-normality">2) Checking For Normality</h4>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="297">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Normal Q-Q plot</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(train, <span class="fu">aes</span>(<span class="at">sample =</span> <span class="fu">residuals</span>(model))) <span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Theoretical Quantiles"</span>, <span class="at">y =</span> <span class="st">"Sample Quantiles"</span>) <span class="sc">+</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Normal Q-Q Plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-30-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>From the above Q-Q plot we can clearly see that the points are not following a straight line, we can see a lot of point at the top and tail which deviate from the straight line. We can also see the presece of outliers. From this we can say that the assumption of normality has been violated.</p>
</section>
<section id="checking-for-linearity" class="level4">
<h4 class="anchored" data-anchor-id="checking-for-linearity">3) Checking for Linearity</h4>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="298">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scale - location Plot</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(train, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fitted</span>(model), <span class="at">y =</span> <span class="fu">sqrt</span>(<span class="fu">abs</span>(<span class="fu">residuals</span>(model))))) <span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Fitted Values"</span>, <span class="at">y =</span> <span class="st">"Sqrt(Standardized Residuals)"</span>) <span class="sc">+</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Scale-Location Plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-31-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>From the above scale vs location plot we can clearly see that there is a presence of curvature, which shows that the assumpotion of linearity is violated.</p>
</section>
<section id="confirming-presence-of-outliers" class="level4">
<h4 class="anchored" data-anchor-id="confirming-presence-of-outliers">4) Confirming presence of outliers</h4>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="299">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Residuals vs Leverage</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(train, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">influence</span>(model)<span class="sc">$</span>hat, <span class="at">y =</span> <span class="fu">residuals</span>(model))) <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Leverage"</span>, <span class="at">y =</span> <span class="st">"Residuals"</span>) <span class="sc">+</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Residuals vs. Leverage"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-32-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>From the above residuals vs leverage plot we can see the presence of outliers which might be points that can influence the results</p>
</section>
<section id="multicollinearity" class="level4">
<h4 class="anchored" data-anchor-id="multicollinearity">5) Multicollinearity</h4>
<p>Multicollinearity has already been tested in the strat of this analysis right after cleaning, to recap we have removed to variables that showed high correlation. Then tested VIF values again to get a result which shows that there was no multicollinearity present in the current model.</p>
</section>
</section>
<section id="goodness-of-fit" class="level3">
<h3 class="anchored" data-anchor-id="goodness-of-fit">Goodness of Fit</h3>
<p>Let’s review the summary of our model again:</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="300">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>
Call:
lm(formula = O2ml_L ~ Depthm + T_degC + Salnty + SiO3uM + Phaeop + 
    NO2uM + NH3uM, data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.7665 -0.2659  0.0344  0.3043  8.0885 

Coefficients:
              Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)  6.4449114  0.1014648   63.519   &lt;2e-16 ***
Depthm      -0.0023178  0.0001356  -17.098   &lt;2e-16 ***
T_degC       0.0649608  0.0026139   24.852   &lt;2e-16 ***
Salnty      -0.0483205  0.0028386  -17.023   &lt;2e-16 ***
SiO3uM      -0.0865234  0.0006587 -131.361   &lt;2e-16 ***
Phaeop       0.3314825  0.0198599   16.691   &lt;2e-16 ***
NO2uM       -0.0897524  0.0526548   -1.705   0.0883 .  
NH3uM        0.0141123  0.0142852    0.988   0.3232    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5051 on 16230 degrees of freedom
Multiple R-squared:  0.8603,    Adjusted R-squared:  0.8602 
F-statistic: 1.428e+04 on 7 and 16230 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>From the above, the high R-squared and Adjusted R-squared values both around 86% suggest a good fit, indicating that the model explains a substantial portion of the variance in O2ml_L.</p>
<p>Let’s verify this with actual vs predicted plot</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="301">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>actual <span class="ot">&lt;-</span> model<span class="sc">$</span>model<span class="sc">$</span>O2ml_L  <span class="co"># Replace with your actual response variable</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(model)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting Predicted vs Actual</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(actual, predicted, <span class="at">xlab =</span> <span class="st">"Actual"</span>, <span class="at">ylab =</span> <span class="st">"Predicted"</span>,</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Actual vs Predicted"</span>)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">col =</span> <span class="st">"red"</span>)  <span class="co"># Add a 45-degree reference line</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-34-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>From the above actual vs predicted plot we can say that the model is a good fit, but there could be an improvement, due to the presence of outliers and some dispersion present.</p>
</section>
<section id="feature-selection" class="level3">
<h3 class="anchored" data-anchor-id="feature-selection">Feature selection</h3>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="302">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>
Call:
lm(formula = O2ml_L ~ Depthm + T_degC + Salnty + SiO3uM + Phaeop + 
    NO2uM + NH3uM, data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.7665 -0.2659  0.0344  0.3043  8.0885 

Coefficients:
              Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)  6.4449114  0.1014648   63.519   &lt;2e-16 ***
Depthm      -0.0023178  0.0001356  -17.098   &lt;2e-16 ***
T_degC       0.0649608  0.0026139   24.852   &lt;2e-16 ***
Salnty      -0.0483205  0.0028386  -17.023   &lt;2e-16 ***
SiO3uM      -0.0865234  0.0006587 -131.361   &lt;2e-16 ***
Phaeop       0.3314825  0.0198599   16.691   &lt;2e-16 ***
NO2uM       -0.0897524  0.0526548   -1.705   0.0883 .  
NH3uM        0.0141123  0.0142852    0.988   0.3232    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5051 on 16230 degrees of freedom
Multiple R-squared:  0.8603,    Adjusted R-squared:  0.8602 
F-statistic: 1.428e+04 on 7 and 16230 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>From these results from the summary of the model we can see that features, ‘Depthm’ , ‘T_degC’, ‘Salnty’, ‘SiO3um’ and ‘Phaeop’ are significant predictors. Features ‘NO2uM’ and ‘NH3uM’ have p value greater than the significance level.</p>
<p>So, based on p-values we can say that features, ‘Depthm’ , ‘T_degC’, ‘Salnty’, ‘SiO3um’ and ‘Phaeop’ are the best to predict the model. 0.3232</p>
<p>Now let’s see which model are best with varying sizes of the predictors and then analyse with various metrics.</p>
<section id="model-selection" class="level4">
<h4 class="anchored" data-anchor-id="model-selection">Model Selection</h4>
<div class="cell" data-outputid="06045a69-e43d-41a3-f4ad-52437d48987c" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="303">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">'leaps'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-outputid="a08845ca-ba84-4fc4-b661-73bf347ef848" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="304">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(O2ml_L <span class="sc">~</span> Depthm <span class="sc">+</span> T_degC <span class="sc">+</span> Salnty <span class="sc">+</span> SiO3uM <span class="sc">+</span> Phaeop <span class="sc">+</span> NO2uM <span class="sc">+</span> NH3uM, <span class="at">data =</span> train)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>rs <span class="ot">&lt;-</span> <span class="fu">summary</span>(reg1)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>rs<span class="sc">$</span>which</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>num_models <span class="ot">&lt;-</span> <span class="fu">length</span>(rs<span class="sc">$</span>rss)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(train)</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>AIC_values <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span><span class="sc">:</span>num_models) <span class="sc">+</span> n <span class="sc">*</span> <span class="fu">log</span>(rs<span class="sc">$</span>rss <span class="sc">/</span> n)  <span class="co"># Calculating AIC values</span></span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>BIC_values <span class="ot">&lt;-</span> <span class="fu">log</span>(n) <span class="sc">*</span> (<span class="dv">1</span><span class="sc">:</span>num_models) <span class="sc">+</span> n <span class="sc">*</span> <span class="fu">log</span>(rs<span class="sc">$</span>rss <span class="sc">/</span> n)  <span class="co"># Calculating BIC Values</span></span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">'The AIC Values are:'</span>)</span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a>AIC_values</span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-19"><a href="#cb50-19" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span><span class="sc">:</span>num_models, AIC_values, <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">xlab =</span> <span class="st">"Number of Predictors"</span>, <span class="at">ylab =</span> <span class="st">"AIC"</span>) <span class="co"># plotting AIC</span></span>
<span id="cb50-20"><a href="#cb50-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-21"><a href="#cb50-21" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span><span class="sc">:</span>num_models, BIC_values, <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">xlab =</span> <span class="st">"Number of Predictors"</span>, <span class="at">ylab =</span> <span class="st">"BIC"</span>) <span class="co"># plotting BIC</span></span>
<span id="cb50-22"><a href="#cb50-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-23"><a href="#cb50-23" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">'The BIC Values are:'</span>)</span>
<span id="cb50-24"><a href="#cb50-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-25"><a href="#cb50-25" aria-hidden="true" tabindex="-1"></a>BIC_values</span>
<span id="cb50-26"><a href="#cb50-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-27"><a href="#cb50-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-28"><a href="#cb50-28" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span><span class="sc">:</span>num_models, rs<span class="sc">$</span>adjr2, <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">xlab =</span> <span class="st">"Number of Predictors"</span>, <span class="at">ylab =</span> <span class="st">"Adjusted R-squared"</span>) <span class="co"># plotting adjusted R^2</span></span>
<span id="cb50-29"><a href="#cb50-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-30"><a href="#cb50-30" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">'The adjusted R^2 values are:'</span>)</span>
<span id="cb50-31"><a href="#cb50-31" aria-hidden="true" tabindex="-1"></a>rs<span class="sc">$</span>adjr2</span>
<span id="cb50-32"><a href="#cb50-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-33"><a href="#cb50-33" aria-hidden="true" tabindex="-1"></a>rs<span class="sc">$</span>rsq <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> rs<span class="sc">$</span>rss <span class="sc">/</span> <span class="fu">sum</span>((train<span class="sc">$</span>O2ml_L <span class="sc">-</span> <span class="fu">mean</span>(train<span class="sc">$</span>O2ml_L))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb50-34"><a href="#cb50-34" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span><span class="sc">:</span>num_models, rs<span class="sc">$</span>rsq, <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">xlab =</span> <span class="st">"Number of Predictors"</span>, <span class="at">ylab =</span> <span class="st">"Goodness of Fit"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="co"># plotting R^2</span></span>
<span id="cb50-35"><a href="#cb50-35" aria-hidden="true" tabindex="-1"></a><span class="fu">title</span>(<span class="st">"R^2 Plot for various predictors"</span>)</span>
<span id="cb50-36"><a href="#cb50-36" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">'R^2 values are:'</span>)</span>
<span id="cb50-37"><a href="#cb50-37" aria-hidden="true" tabindex="-1"></a>rs<span class="sc">$</span>rsq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A matrix: 7 × 8 of type lgl</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">(Intercept)</th>
<th data-quarto-table-cell-role="th" scope="col">Depthm</th>
<th data-quarto-table-cell-role="th" scope="col">T_degC</th>
<th data-quarto-table-cell-role="th" scope="col">Salnty</th>
<th data-quarto-table-cell-role="th" scope="col">SiO3uM</th>
<th data-quarto-table-cell-role="th" scope="col">Phaeop</th>
<th data-quarto-table-cell-role="th" scope="col">NO2uM</th>
<th data-quarto-table-cell-role="th" scope="col">NH3uM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">1</td>
<td>TRUE</td>
<td>FALSE</td>
<td>FALSE</td>
<td>FALSE</td>
<td>TRUE</td>
<td>FALSE</td>
<td>FALSE</td>
<td>FALSE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">2</td>
<td>TRUE</td>
<td>TRUE</td>
<td>FALSE</td>
<td>FALSE</td>
<td>TRUE</td>
<td>FALSE</td>
<td>FALSE</td>
<td>FALSE</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">3</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>FALSE</td>
<td>TRUE</td>
<td>FALSE</td>
<td>FALSE</td>
<td>FALSE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">4</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>FALSE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>FALSE</td>
<td>FALSE</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">5</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>FALSE</td>
<td>FALSE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">6</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>FALSE</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">7</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The AIC Values are:"
[1] "The BIC Values are:"
[1] "The adjusted R^2 values are:"
[1] "R^2 values are:"</code></pre>
</div>
<div class="cell-output cell-output-display">
<style>
.list-inline {list-style: none; margin:0; padding: 0}
.list-inline>li {display: inline-block}
.list-inline>li:not(:last-child)::after {content: "\00b7"; padding: 0 .5ex}
</style>
<ol class="list-inline"><li>-19491.9852272089</li><li>-21212.0255597217</li><li>-21597.3575765951</li><li>-21890.3969374089</li><li>-22173.7958990925</li><li>-22173.893772217</li><li>-22172.8701750368</li></ol>
</div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-37-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<style>
.list-inline {list-style: none; margin:0; padding: 0}
.list-inline>li {display: inline-block}
.list-inline>li:not(:last-child)::after {content: "\00b7"; padding: 0 .5ex}
</style>
<ol class="list-inline"><li>-19484.2901177555</li><li>-21196.6353408149</li><li>-21574.2722482348</li><li>-21859.6164995952</li><li>-22135.3203518254</li><li>-22127.7231154964</li><li>-22119.0044088629</li></ol>
</div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-37-output-6.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<style>
.list-inline {list-style: none; margin:0; padding: 0}
.list-inline>li {display: inline-block}
.list-inline>li:not(:last-child)::after {content: "\00b7"; padding: 0 .5ex}
</style>
<ol class="list-inline"><li>0.835078446951443</li><li>0.851663774425713</li><li>0.855151313305888</li><li>0.857750640188316</li><li>0.860220359641389</li><li>0.860229806565329</li><li>0.860229599472596</li></ol>
</div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-37-output-8.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<style>
.list-inline {list-style: none; margin:0; padding: 0}
.list-inline>li {display: inline-block}
.list-inline>li:not(:last-child)::after {content: "\00b7"; padding: 0 .5ex}
</style>
<ol class="list-inline"><li>0.835088604095807</li><li>0.851682045809043</li><li>0.855178076012058</li><li>0.857785683449955</li><li>0.860263403196343</li><li>0.860281455340386</li><li>0.86028985646611</li></ol>
</div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-37-output-10.png" class="img-fluid"></p>
</div>
</div>
<p>The best models according to size of the predictors:</p>
<ol type="1">
<li><p><strong>Model 1</strong>: $ O2ml_L = <em>0 + </em>{SiO3uM} SiO3uM $</p></li>
<li><p><strong>Model 2</strong>: $ O2ml_L = <em>0 + </em>{Depthm} Depthm + _{SiO3uM} SiO3uM $</p></li>
<li><p><strong>Model 3</strong>: $ O2ml_L = <em>0 + </em>{Depthm} Depthm + <em>{T_degC} T_degC + </em>{SiO3uM} SiO3uM $</p></li>
<li><p><strong>Model 4</strong>: $ O2ml_L = <em>0 + </em>{Depthm} Depthm + <em>{T_degC} T_degC + </em>{SiO3uM} SiO3uM + _{Phaeop} Phaeop $</p></li>
<li><p><strong>Model 5</strong>: $ O2ml_L = <em>0 + </em>{Depthm} Depthm + <em>{T_degC} T_degC + </em>{Salnty} Salnty + <em>{SiO3uM} SiO3uM + </em>{Phaeop} Phaeop $</p></li>
<li><p><strong>Model 6</strong>: $ O2ml_L = <em>0 + </em>{Depthm} Depthm + <em>{T_degC} T_degC + </em>{Salnty} Salnty + <em>{SiO3uM} SiO3uM + </em>{Phaeop} Phaeop + _{NO2uM} NO2uM $</p></li>
<li><p><strong>Model 7</strong>: $ O2ml_L = <em>0 + </em>{Depthm} Depthm + <em>{T_degC} T_degC + </em>{Salnty} Salnty + <em>{SiO3uM} SiO3uM + </em>{Phaeop} Phaeop + <em>{NO2uM} NO2uM + </em>{NH3uM} NH3uM $</p></li>
</ol>
<p>From the above plots these are the best models selected by each of the metric:</p>
<p><strong>Best Model by AIC : (The model with lowest AIC value among all is considered best model)</strong></p>
<p>Model 6:</p>
<p>$ O2ml_L = <em>0 + </em>{Depthm} Depthm + <em>{T_degC} T_degC + </em>{Salnty} Salnty + <em>{SiO3uM} SiO3uM + </em>{Phaeop} Phaeop + _{NO2uM} NO2uM $</p>
<p><strong>Best Model by BIC: (The model with lowest BIC value among all is considered best model)</strong></p>
<p>Model 5:</p>
<p>$ O2ml_L = <em>0 + </em>{Depthm} Depthm + <em>{T_degC} T_degC + </em>{Salnty} Salnty + <em>{SiO3uM} SiO3uM + </em>{Phaeop} Phaeop $</p>
<p><strong>Best Model by Adjusted R^2: (The model with highest adjusted R^2 value among all is considered best model)</strong></p>
<p>Model 6:</p>
<p>$ O2ml_L = <em>0 + </em>{Depthm} Depthm + <em>{T_degC} T_degC + </em>{Salnty} Salnty + <em>{SiO3uM} SiO3uM + </em>{Phaeop} Phaeop + _{NO2uM} NO2uM $</p>
<p><strong>Best Model by R^2 : (The model with highest R^2 value among all is considered best model)</strong></p>
<p>Model 7:</p>
<p>$ O2ml_L = <em>0 + </em>{Depthm} Depthm + <em>{T_degC} T_degC + </em>{Salnty} Salnty + <em>{SiO3uM} SiO3uM + </em>{Phaeop} Phaeop + <em>{NO2uM} NO2uM + </em>{NH3uM} NH3uM $</p>
<p>From above we can see that various metrics have selected models with various size of predictor sizes. Here in the above selection when selecting between various metric it is to be noted that model 5, model 6 and model 7 have very close metric values when it comes to all metrics AIC, BIC, R^2 and adjusted R^2. The difference between these models was in decimals places when it comes to comparission of metrics.</p>
<p>Let’s confirm the best model by also testing with MSPE values.</p>
<div class="cell" data-outputid="c0f63836-24b5-4153-fb9f-97741bceadf6" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="305">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(O2ml_L <span class="sc">~</span> Depthm <span class="sc">+</span> T_degC <span class="sc">+</span> Salnty <span class="sc">+</span> SiO3uM <span class="sc">+</span> Phaeop <span class="sc">+</span> NO2uM <span class="sc">+</span> NH3uM, <span class="at">data =</span> train)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>rs <span class="ot">&lt;-</span> <span class="fu">summary</span>(reg1)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>rs<span class="sc">$</span>which</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true">
<caption>A matrix: 7 × 8 of type lgl</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th" scope="col">(Intercept)</th>
<th data-quarto-table-cell-role="th" scope="col">Depthm</th>
<th data-quarto-table-cell-role="th" scope="col">T_degC</th>
<th data-quarto-table-cell-role="th" scope="col">Salnty</th>
<th data-quarto-table-cell-role="th" scope="col">SiO3uM</th>
<th data-quarto-table-cell-role="th" scope="col">Phaeop</th>
<th data-quarto-table-cell-role="th" scope="col">NO2uM</th>
<th data-quarto-table-cell-role="th" scope="col">NH3uM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">1</td>
<td>TRUE</td>
<td>FALSE</td>
<td>FALSE</td>
<td>FALSE</td>
<td>TRUE</td>
<td>FALSE</td>
<td>FALSE</td>
<td>FALSE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">2</td>
<td>TRUE</td>
<td>TRUE</td>
<td>FALSE</td>
<td>FALSE</td>
<td>TRUE</td>
<td>FALSE</td>
<td>FALSE</td>
<td>FALSE</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">3</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>FALSE</td>
<td>TRUE</td>
<td>FALSE</td>
<td>FALSE</td>
<td>FALSE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">4</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>FALSE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>FALSE</td>
<td>FALSE</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">5</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>FALSE</td>
<td>FALSE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th" scope="row">6</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>FALSE</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th" scope="row">7</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
<td>TRUE</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The above code is a table showing best features for each size of the predictors</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="306">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting models for best predictors in each size</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(O2ml_L <span class="sc">~</span> Depthm, <span class="at">data =</span> train)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(O2ml_L <span class="sc">~</span> Depthm <span class="sc">+</span> SiO3uM, <span class="at">data =</span> train)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(O2ml_L <span class="sc">~</span> Depthm <span class="sc">+</span> T_degC <span class="sc">+</span> SiO3uM, <span class="at">data =</span> train)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(O2ml_L <span class="sc">~</span> Depthm <span class="sc">+</span> T_degC <span class="sc">+</span> Phaeop <span class="sc">+</span> SiO3uM, <span class="at">data =</span> train)</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>model5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(O2ml_L <span class="sc">~</span> Depthm <span class="sc">+</span> T_degC <span class="sc">+</span> Salnty <span class="sc">+</span> SiO3uM<span class="sc">+</span> Phaeop, <span class="at">data =</span> train)</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>model6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(O2ml_L <span class="sc">~</span> Depthm <span class="sc">+</span> T_degC <span class="sc">+</span> Salnty <span class="sc">+</span> SiO3uM<span class="sc">+</span> Phaeop <span class="sc">+</span> NO2uM, <span class="at">data =</span> train)</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>model7 <span class="ot">&lt;-</span> <span class="fu">lm</span>(O2ml_L <span class="sc">~</span> Depthm <span class="sc">+</span> T_degC <span class="sc">+</span> Salnty <span class="sc">+</span> SiO3uM<span class="sc">+</span> Phaeop <span class="sc">+</span> NO2uM <span class="sc">+</span>NH3uM, <span class="at">data =</span> train)</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-outputid="707751e5-2bcb-43b8-8112-a90f3ca521b3" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="307">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating MSPE Values for each model</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>calculate_mspe <span class="ot">&lt;-</span> <span class="cf">function</span>(model, test_data) {</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> test_data)</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>((test_data<span class="sc">$</span>O2ml_L <span class="sc">-</span> predictions)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>mspe1 <span class="ot">&lt;-</span> <span class="fu">calculate_mspe</span>(model1, test)</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>mspe2 <span class="ot">&lt;-</span> <span class="fu">calculate_mspe</span>(model2, test)</span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>mspe3 <span class="ot">&lt;-</span> <span class="fu">calculate_mspe</span>(model3, test)</span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>mspe4 <span class="ot">&lt;-</span> <span class="fu">calculate_mspe</span>(model4, test)</span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>mspe5 <span class="ot">&lt;-</span> <span class="fu">calculate_mspe</span>(model5, test)</span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a>mspe6 <span class="ot">&lt;-</span> <span class="fu">calculate_mspe</span>(model6, test)</span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a>mspe7 <span class="ot">&lt;-</span> <span class="fu">calculate_mspe</span>(model7, test)</span>
<span id="cb54-15"><a href="#cb54-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-16"><a href="#cb54-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-17"><a href="#cb54-17" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"MSPE for Model 1:"</span>, mspe1))</span>
<span id="cb54-18"><a href="#cb54-18" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"MSPE for Model 2:"</span>, mspe2))</span>
<span id="cb54-19"><a href="#cb54-19" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"MSPE for Model 3:"</span>, mspe3))</span>
<span id="cb54-20"><a href="#cb54-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"MSPE for Model 4:"</span>, mspe4))</span>
<span id="cb54-21"><a href="#cb54-21" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"MSPE for Model 5:"</span>, mspe5))</span>
<span id="cb54-22"><a href="#cb54-22" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"MSPE for Model 6:"</span>, mspe6))</span>
<span id="cb54-23"><a href="#cb54-23" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"MSPE for Model 7:"</span>, mspe7))</span>
<span id="cb54-24"><a href="#cb54-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-25"><a href="#cb54-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-26"><a href="#cb54-26" aria-hidden="true" tabindex="-1"></a>mspes <span class="ot">&lt;-</span> <span class="fu">c</span>(mspe1, mspe2, mspe3, mspe4, mspe5, mspe6,mspe7)</span>
<span id="cb54-27"><a href="#cb54-27" aria-hidden="true" tabindex="-1"></a>best_model_size <span class="ot">&lt;-</span> <span class="fu">which.min</span>(mspes)</span>
<span id="cb54-28"><a href="#cb54-28" aria-hidden="true" tabindex="-1"></a>best_mspe <span class="ot">&lt;-</span> mspes[best_model_size]</span>
<span id="cb54-29"><a href="#cb54-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-30"><a href="#cb54-30" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Best Model (by MSPE) Size:"</span>, best_model_size))</span>
<span id="cb54-31"><a href="#cb54-31" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Lowest MSPE:"</span>, best_mspe))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "MSPE for Model 1: 0.655433188328069"
[1] "MSPE for Model 2: 0.233821960709644"
[1] "MSPE for Model 3: 0.230057677611918"
[1] "MSPE for Model 4: 0.227806616239863"
[1] "MSPE for Model 5: 0.222951882360932"
[1] "MSPE for Model 6: 0.223018899466372"
[1] "MSPE for Model 7: 0.223282001171033"
[1] "Best Model (by MSPE) Size: 5"
[1] "Lowest MSPE: 0.222951882360932"</code></pre>
</div>
</div>
<p>From the above result we can see that model 5 i.e.&nbsp;:</p>
<p>$ O2ml_L = <em>0 + </em>{Depthm} Depthm + <em>{T_degC} T_degC + </em>{Salnty} Salnty + <em>{SiO3uM} SiO3uM + </em>{Phaeop} Phaeop $</p>
<p>has the best fit, since it has the lowest MSPE value.</p>
<p>Even here we can see from the result from Model 4 to Model 7 the MSPE values are very similar with minute difference in decimals.</p>
<p>After the complete analysis from various metrics, I will be choosing Model 5:</p>
<p>$ O2ml_L = <em>0 + </em>{Depthm} Depthm + <em>{T_degC} T_degC + </em>{Salnty} Salnty + <em>{SiO3uM} SiO3uM + </em>{Phaeop} Phaeop $</p>
<p>as the best model.</p>
<p>Reason:</p>
<ul>
<li>Less predictor make it simple to make predictions</li>
<li>BIC has choosen model 5 and having the lowest BIC, says us that Model 5 is preferable for balancing model fit and complexity.</li>
<li>MSPE has choosen model 5, it suggests that additional predictors dont have an impact in improvement of the model.</li>
</ul>
<div class="cell" data-outputid="a5c89152-b57b-4703-ca65-f75c3ccfb60a" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="308">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">'car'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Since we have selected model 5 as the best model, let’s verify if it has any collinearity</p>
<div class="cell" data-outputid="31d7acd8-0eb3-496a-c03a-6429c13a7d8f" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="309">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>calculate_vifs <span class="ot">&lt;-</span> <span class="cf">function</span>(model) {</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">vif</span>(model)</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculation VIF values</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>models <span class="ot">&lt;-</span> <span class="fu">list</span>(model5)</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>vifs <span class="ot">&lt;-</span> <span class="fu">calculate_vifs</span>(model5)</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>cond_number <span class="ot">&lt;-</span> <span class="fu">kappa</span>(model5)</span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"VIFs:"</span>)</span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(vifs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "VIFs:"
  Depthm   T_degC   Salnty   SiO3uM   Phaeop 
3.961719 3.970993 1.032122 3.285528 1.268528 </code></pre>
</div>
</div>
<p>From the above results we can say that there is no collinearity present in this 5 predictor model, since all VIF values are below 5.</p>
<p>Finally let’s have a final look at the summary at our best selected model i.e.&nbsp;model 5</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="310">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>
Call:
lm(formula = O2ml_L ~ Depthm + T_degC + Salnty + SiO3uM + Phaeop, 
    data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.7491 -0.2664  0.0342  0.3044  8.0849 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  6.4205975  0.1003686   63.97   &lt;2e-16 ***
Depthm      -0.0022869  0.0001336  -17.12   &lt;2e-16 ***
T_degC       0.0658894  0.0025517   25.82   &lt;2e-16 ***
Salnty      -0.0481107  0.0028359  -16.96   &lt;2e-16 ***
SiO3uM      -0.0864192  0.0006560 -131.75   &lt;2e-16 ***
Phaeop       0.3235582  0.0187262   17.28   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5052 on 16232 degrees of freedom
Multiple R-squared:  0.8603,    Adjusted R-squared:  0.8602 
F-statistic: 1.999e+04 on 5 and 16232 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>From the results from our best model, we can see that, we have a solid adjusted R^2 value of 86% which suggest that 86% of variance dissolved in oxygen levels is explained by the model. From the P values also we can see that all of the predictors have significant impact since the p-values for all are very low.</p>
<p>Let’s have a final look at diagnostics with this best model with 5 predictors</p>
<div class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="311">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))  <span class="co"># Arrange plots in a 2x2 grid</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Regression_Analysis_Oceongrahpic_data_files/figure-html/cell-44-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Again, we can see very similar graphs and we can also see similar violations when it comes to normality, constant variance and presence of outliers. So, here the results are similar to 7 predictor model.</p>
<p>Overall, we can conclude that the model with 5 predictors - Depth, temperature of water, Salanity of water,Silicate concentration and Phaeophytin concentration are the best predictors to predict the oxygen concentration. A model which can explain 86% of variance dissolved in oxygen levels is achieved. Better results can be obtained if more examination was done on outlier values and trying out non-linear fitting.</p>
</section>
</section>
<section id="report" class="level2">
<h2 class="anchored" data-anchor-id="report">Report</h2>
<section id="topic-understanding-oxygen-dynamics-in-oceanographic-data-the-influence-of-environmental-variables" class="level3">
<h3 class="anchored" data-anchor-id="topic-understanding-oxygen-dynamics-in-oceanographic-data-the-influence-of-environmental-variables">Topic: <strong>Understanding Oxygen Dynamics in Oceanographic data : The Influence of Environmental Variables</strong></h3>
<section id="introduction" class="level5">
<h5 class="anchored" data-anchor-id="introduction">1. Introduction</h5>
<p>Oceanic oxygen concentrations are fundamental for marine ecosystems, supporting biodiversity and influencing key biogeochemical processes. Oxygen levels in sea water can fluctuate due to various environmental factors. This study investigates how depth, temperature, salinity, and various nutrients influence oxygen concentration in seawater within California Sea Coast. A similar study related to this data was done on Sea Surface Temperature by Sivasankari, Manickavasagam &amp; R, Anandan.{(2020). Regression Analysis on Sea Surface Temperature. 10.1007/978-981-15-3284-9_68}. In their paper they analysed sea surface temperature over salinity using different methods like linear regression, decision tree, random forest, and SVR. They have performed these various regression analysis and compared the models. They found that temperature and salinity do not have that strog of a relation.</p>
<p>The dataset used in this analysis is a subset of bottle dataset maintained by California Cooperative Oceanic Fisheries Investigations (CalCOFI). This analysis focuses on the years 2017-2021. This observational study includes parameters such as temperature, salinity, dissolved oxygen, and nutrients. CalCOFI first collects Seawater from various sampling depths using 10-liter Niskin bottles attached to a 24-place CTD-Rosette frame. Then they measure environmental parameters using chemical analyses (i.e.&nbsp;titrations and assays) from the seawater samples. Finally CalCOFI compiles the data into the Bottle Database. CalCOFI collectes this data to to understand and predict the effects of climate change on marine ecosystems.</p>
<p>The primary questions of interest in this research are:</p>
<ol type="1">
<li>Which environmental variables are the most important predictors of oxygen concentration?</li>
<li>How well can a linear model explain the observed variability in oxygen levels?</li>
<li>Is depth is a significant predictor for response variable - oxygen concentration?</li>
<li>Is there a significant relationship between any of the predictors (Depthm, T_degC, Salnty, SiO3uM, Phaeop, NO2uM, and NH3uM) and the dissolved oxygen levels (O2ml_L)</li>
</ol>
</section>
<section id="methodsresults" class="level5">
<h5 class="anchored" data-anchor-id="methodsresults">2. Methods/Results</h5>
<p>The CalCOFI dataset taken from CalCOFI research program website. Two datasets were taken from this site, one is bottle dataset and other a cast dataset which contains corresponding date and year of recorded data in bottle dataset. These two dataset were used to filtere and to include the years 2017-2021 and relevant physical and nutrient variables. The main variables used in this analysis are:</p>
<p><strong>Dependent Variable</strong>:</p>
<p>O2ml_L - Oxygen in mL/L - Milliliters of dissolved oxygen per Liter seawater</p>
<p><strong>Independent Variables</strong>:</p>
<p>Depthm (Depth in meters) T_degC (Temperature of water) (Degrees C) Salnty (Salinity of water) (Practical Salinity Scale)</p>
<p>PO4µM - Phosphate concentration (micro Moles per Liter) SiO3µM -Silicate concentration - (micro Moles per Liter) NO3µM - Nitrate concentration - (micro Moles per Liter) Phaeop -Phaeophytin concentration measured fluorometrically (µg/L) NO2uM - Nitrite concentration (micro Moles per Liter) NH3uM - Ammonium concentration - (micro Moles per Liter)</p>
<p>Data Cleaning was performed first, where it was found out that various columns had missing values. Columns like temperature and salinity which had missing values less 10 were removed. To handle remaining missing values, first skewness was checked using density plots. These density plots can be see below.</p>
<p><img src="https://drive.google.com/uc?id=1QBpRoNigXFnplMXhwmW4ftrEvE_vdO2_" alt="Drawing" style="width: 350px;"></p>
<p><img src="https://lh3.googleusercontent.com/drive-viewer/AKGpihY6ftN25xb0v3XPvE2-CN7DngG4cijxa_xKoP96tv3MU3a5xphXr3ZrTD4f3b4EQxL-r9Q6t2Xa10JOhaEp0QReLqYPzhQhi5U=s1600-rw-v1" alt="Drawing" style="width: 400px;"></p>
<p><img src="https://lh3.googleusercontent.com/drive-viewer/AKGpihaFTcNCOVuCypFsB839WP3hOGU5JZ9KcNu9Z1gVM70x03-79h6uwAzUqy6jIVN7jtzjDJKF0pJjUD-T7-TsGQlkqCuH0xM9VA=s2560" alt="Drawing" style="width: 400px;"></p>
<p>After verifying the density plots, due to the presence of skewness in all the variables having missing values, median was choosen as the imputaition method to replace the missing values. Some unrealistic values were removed in all the columns . Summary statistics was compared before and after cleaning to ensure there were no major changes.</p>
<p>To answer the questions to find the best predictors it was decided that regression modelling, particularly multiple regression was found suitable. First the dataset was randomly split into traning and test set with 80% of the data into traning set and 20% of data for testing. Initailly a correlation plot was plotted to examine which independent variables have high correlation among each other.</p>
<p><img src="https://lh3.googleusercontent.com/drive-viewer/AKGpihYFwvfawi-et4U1ys0kCLpAuzSlxfoOQDq_w4K1iiSRPaYPLVAI3RrBrRX2jem4Pu6g0kee7iSfZRF2Qu3thnR5IDkK5eWamA=s2560" alt="Drawing" style="width: 400px;"></p>
<p>It was observed that ‘PO4uM’, ‘NO3uM’ and ‘SiO3uM’ had a very high correlation among other variables from the above scatter plot. To verify this first a multiple linear regression model was fitted and variance inflation factors (VIFs) was observed for various features. It was confirmed that ‘PO4uM’, ‘NO3uM’ and ‘SiO3uM’ had high correlation due to their high values. To reduce multicollinearity ‘PO4uM’, ‘NO3uM’ features were decided to be removed from the analysis since they have VIF values more than 100. The multiple linear regresssion was done again and multicollinearity was checked for remaining seven predictors. It was found that there was no presence of multicollinearity in these seven predictor variables.</p>
<p>Regression analysis was now performed on the remaining seven predictor variables. Summary of regression model was analysed and it was found that 86% of variance dissolved in oxygen levels is explained by the model, this is evident from the Adjusted <span class="math inline">\(R^2\)</span> value of 86% from the model. It was also observed that that all the predictors except nitrite concentration (‘NO2uM’) and Ammonium concentration (‘NH3uM’) are statistically very good predictors with the response variable - O2ml_L i.e.&nbsp;oxygen concentration.</p>
<p>A t-test was performed to check if depth was a strong predictor for the response variable oxygen concentration. Due the very low p-value observed null hypothesis was rejected and it was concluded that there is a statistically significant relationship between Depthm and O2ml_L features.</p>
<p>To find if there is a significant relationship between any of the predictors (Depthm, T_degC, Salnty, SiO3uM, Phaeop, NO2uM, and NH3uM) and the dissolved oxygen levels (O2ml_L), hypothesis test with ANOVA was used. From the results of the test it was observed that Depthm, T_degC, Salnty, SiO3uM, and Phaeop had very low p-values and NO2uM and NH3uM had p-values above significance level of 0.01. Since more than one variable which has significant relation with the response variable was present, there was significant evidence to reject the null hypothesis at the α = 0.01 level. So, it was seen that that at least one of the predictors (Depthm, T_degC, Salnty, SiO3uM, or Phaeop) is significantly associated with the response variable, O2ml_L. NO2uM and NH3uM do not significantly explain the variance in O2ml_L, as their p-values are greater than 0.01.</p>
<p>To check for validity of Regression and ANOVA assumptions Diagnostic Analysis was performed. Various diagnostic plots were plotted to check for violations.</p>
<ol type="1">
<li>Residuals Vs Fitted Plot</li>
</ol>
<p><img src="https://lh3.googleusercontent.com/drive-viewer/AKGpiha5CP-tDr5sZF9xbV9BtHUptX5-ROxkqvLNn2w-92iJmV-VPzRZU52K-esBnuI89sumUxK__mchN3n4nyhTqm2WmQEUAyTFoQ=s2560" alt="Drawing" style="width: 400px;"></p>
<p>From the above Residuals vs Fitted plot the presence of some outliers and also right towards the end of the plot there are many values which have a lower value compared to others. There is a clear visible downward spike, so the constant variance assumption has been violated here.</p>
<ol start="2" type="1">
<li>Normal Q-Q Plot</li>
</ol>
<p><img src="https://lh3.googleusercontent.com/drive-viewer/AKGpihb4PBotUxtbUQyGQaE5zvAoajwyDzspXUUzAao55IWk13cgeNXRQEZtse_BF-SIeGHO9xgOuMSOmORpzIPsdHQKO4_2I7_8-Ws=s2560" alt="Drawing" style="width: 400px;"></p>
<p>From the above Q-Q plot it is clearly seen that the points are not following a straight line, it can be seen that a lot of points at the top and tail deviate from the straight line. The presece of outliers is also evident. So, the assumption of normality has been violated.</p>
<ol start="3" type="1">
<li>Scale and Location Plot</li>
</ol>
<p><img src="https://lh3.googleusercontent.com/drive-viewer/AKGpihY9Et__vtfdMl8PtTRhhl_5UWmZg520uNri5LGHPg11gLKVioLCVQA8p84PklFvystqMJjaLpajoogon1d_vsYHH_cShllXGqI=s2560" alt="Drawing" style="width: 400px;"></p>
<p>From the above scale vs location plot it can be clearly seen that there is a presence of curvature, which shows that the assumption of linearity is violated.</p>
<ol start="4" type="1">
<li>Residual and Leverage Plot</li>
</ol>
<p><img src="https://lh3.googleusercontent.com/drive-viewer/AKGpihY9ZXoK5eK7rzx_WjOgXIuj5QbbiPj01fCIcvUrgUAn-0x5dUlRPUXmqwSmCATnNxzM-wYj7qybJZF-HlgnURcmAsJFfYdgziU=s2560" alt="Drawing" style="width: 400px;"></p>
<p>From the above residuals vs leverage plot it the presence of outliers which might be points that can influence the results is evident.</p>
<p>The goodness of fit for the model was analysed with the summary statistics of the model. From the summary of the multiple linear regression model a high R-squared and Adjusted R-squared values both around 86% was found. This suggest a good fit, indicating that the model explains a substantial portion of the variance in O2ml_L. This result was further verified by plotting actual vs predicted graph.</p>
<p><img src="https://lh3.googleusercontent.com/drive-viewer/AKGpihY0bGv1amAhLxrE2XFc-CuZZdEu89Jj-HUR2II3ntStLGFcfdsQGrqG4oVyjyic64BUeqrgv4fu9R_DFYKkn2nViDRc47c3pLE=s2560" alt="Drawing" style="width: 400px;"></p>
<p>From the above actual vs predicted graph it can be said that the model is a good fit, but there could be an improvement, due to the presence of outliers and some dispersion present.</p>
<p>To identify the most best predictive model, a combination of metrics (AIC, BIC, MSPE, R-squared, and adjusted R-squared) was considered. All of these metrics had almost similar results with models with 5,6 and 7 features. A model with five predictors (Depthm, T_degC, Salnty, SiO3uM, Phaeop) was choosen as the best model for this analysis. This was due to the fact that less predictor make it simple to make predictions and BIC has choosen model 5 and having the lowest BIC, says us that Model 5 is preferable for balancing model fit and complexity. MSPE has choosen model 5, it suggests that additional predictors dont have an impact in improvement of the model.</p>
<p>A summary of this five preictor model was revealed that all the features are very good predictors due to the presence of low p-values. The adjusted <span class="math inline">\(R^2\)</span> value of 86% remained same from initail model Finally diagnostics and collinearity tests were done to this five predictor model. It was observed that the diagnostics remained with simialar residual grpahs with violations in constant variance, normality and presence of outliers and violation of linearity. It was found that this five predictor model has no collinearity since all features had VIF values less than 5.</p>
<p><strong>Conclusion</strong></p>
<p>This analysis highlights the strong influence of environmental variables on oxygen concentration in sea water in the California Sea Coast. It was found that depth, temperature, salinity, silicate concentration, and phaeophytin concentration all emerged as significant predictors. The selected model provides a solid foundation for understanding oxygen variability as 86% of variance dissolved in oxygen levels is explained by the model. The diagnostics revealed various violations of assumptions. t-test and ANOVA further supported the importance of the selected predictors. A t-test confirmed a strong influence of depth on oxygen concentration. ANOVA indicated at least one predictor was significantly associated with oxygen. A further research could include finding the reasons behind the violations of assumptions of regression by the model. Various transformations can be tested with model to reduce the violations. Additional features like chlorophyll-a can be included and be teseted as predictors with the model.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>